### PR TITLE
Spencer notes first draft

### PR DESCRIPTION
**Pull request by cspencerjones**
If you could have a quick look through and give me some feedback that'd be great. I haven't updated README.md to add my file but I can do that too if you want. Thanks!

### CODE REVIEW

**Comment by rabernat** [comment]
Overall this looks good in terms of the topics. Perhaps the Munk k_v stuff should come first though?

I would probably make it a bit longer and more detailed if you can.

I will have time to go over in more detail after my lecture tomorrow.

**Comment by cspencerjones** [comment]
Do you mind looking again? I swapped the Munk and Stommel-Arons sections and added a bit more detail.

**Comment by rabernat** [comment]
This is great. A few comments, if you have time:

- A side-view sketch (lat vs. depth) might be helpful as well. You don't have to put this in the notebook, but perhaps on the board.
- How do you determine the zonal flow in the Stommel Aarons solution? In the full-depth problem you can define a streamfunction because the flow is 2D non-divergent. I don't have a textbook in front of me right now and I don't remember the answer. But this seems important in order to quantitatively determine the strength of the recirculation and DWBC.  I seem to recall that a property of the solution is that the DBWC maximum transport is 2 * Q_s.
- It might be nice to include some sort of observational evidence related to DWBC, since this is a notable property of the solution. Oxygen data show this well, e.g. http://whp-atlas.ucsd.edu/atlantic/maps/oxygen/propmaps.htm. O2


A few python comments. In the following code there are a few issues.
```python
import copy
ds2=copy.deepcopy(ds)
ds2['data']=ds['data']+4*10**6*np.tan(np.deg2rad(ds['lat']))*15*10**6/4/10**13
#ds2=ds2.where(ds.data==0)
ds2.where(ds.data==0).where((ds.lat<60) & (ds.lat>-60)).to_array().plot(vmin=-2,vmax=2, aspect=1.5,size=10)
plt.ylim(-60,60) 
plt.title('Predicted meridional velocity in the deep ocean, integrated vertically (units are $m^2/s$)',fontsize=20)
```

- No need to do any of this copy / deepcopy business
- Where is for masking data, not selecting data. Use `.sel` instead to select a range.

The following (untested) code should probably do the trick.

```python
V = ds['data'] + 4*10**6*np.tan(np.deg2rad(ds['lat']))*15*10**6/4/10**13
V.where(ds.data==0).sel(lat=slice(-60, 60)).plot(vmax=2, cmap='RdBu_r')
```

**Comment by rabernat** [comment]
Ok I will merge this now. You can still update it later if you want.

**Pull request merged**
